# Generated by Django 4.0.4 on 2022-05-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_abc_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='task',
            field=models.CharField(default='Равна ли С сумме A и B?', max_length=256),
        ),
    ]
