# Generated by Django 4.0.4 on 2022-05-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_abc_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
