# Generated by Django 4.0.4 on 2022-05-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_abc_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='pub_date',
        ),
    ]
